export interface Product {
  slug: string;
  name: string;
  img: string | null;
  price: string | null;
  soldout: boolean;
  cats: string[];
  desc?: string;
}

export const CATALOG: Product[] = [
  { slug: 'vintage-fendi-bracelet-watch-gold', name: 'Vintage Fendi Bracelet Watch - Gold', img: 'https://assets.bigcartel.com/product_images/421574505/38232BDD-44BC-4496-A6B0-7890172C307B_1_102_o.jpeg?auto=format&fit=max&w=800', price: '750.0', soldout: false, cats: ['One-of-One'], desc: 'Vintage gold-tone Fendi Orologi 660L watch featuring a sleek square case with a refined, minimalist profile and gold dial featuring Roman numeral and round index markers.\nStainless steel bracelet with a polished, jewelry-like finish.\nQuartz movement.\nFold-over clasp closure for secure wear.\nWater resistant up to 30m.\nDesigned to be worn as both a timepiece and statement accessory.\nWatch is not currently functioning.\nSwiss made.\nMinor signs of wear.\nComplimentary link removal available upon request.\nSourced with love in Los Angeles, CA <3' },
  { slug: 'vintage-fendi-bracelet-watch-silver', name: 'Vintage Fendi Bracelet Watch - Silver', img: 'https://assets.bigcartel.com/product_images/421574580/3B69A49A-B88B-4DBA-8DC3-59590006AE50_1_102_o.jpeg?auto=format&fit=max&w=800', price: '500.0', soldout: false, cats: ['One-of-One'], desc: 'Vintage silver-tone Fendi Orologi 660L watch.\nFits approx. 5.75–6 in wrist (petite fit).\nSleek square case with a refined, minimalist profile.\nSilver-white dial featuring Roman numeral and round index markers.\nStainless steel bracelet with a polished, jewelry-like finish.\nQuartz movement.\nFold-over clasp closure for secure wear.\nWater resistant up to 30m.\nDesigned to be worn as both a timepiece and statement accessory.\nWatch is functioning.\nSwiss made.\nMinor signs of wear.\nSourced with love in Los Angeles, CA <3' },
  { slug: 'vintage-collar-choker', name: 'Vintage Collar Choker', img: 'https://assets.bigcartel.com/product_images/415873314/IMG_7428.jpeg?auto=format&fit=max&w=800', price: '150.0', soldout: false, cats: ['Best Sellers', 'Necklaces', 'Statement'], desc: 'Vintage-inspired.\n14k gold-plated brass.\nThick, structured choker with a smooth polished finish.\n4.5 in diameter.\n1.75 in thickness.\nOne size – adjustable, flexible, and easily moldable for a custom fit.' },
  { slug: 'isla-necklace', name: 'Isla Statement Mirrored Necklace', img: 'https://assets.bigcartel.com/product_images/409155333/91ABA159-7EAA-4AF5-A5C7-4AB15B3AD8B2_1_102_a.jpeg?auto=format&fit=max&w=800', price: '215.0', soldout: false, cats: ['Best Sellers', 'Necklaces', 'Statement'], desc: 'Gold-plated brass necklace with cascading hand-set mirrored accents.\nMultiple hand-set mirrored accents for a dazzling effect.\nAdjustable chain for a comfortable, custom fit.\nHandmade - unique variations and slight irregularities.\nThe perfect statement piece!!' },
  { slug: 'cora-wrap-scarf-necklace', name: 'Cora Wrap Scarf Necklace', img: 'https://assets.bigcartel.com/product_images/412258665/4975E8AC-83EA-444F-AC44-39014DF30829.jpg?auto=format&fit=max&w=800', price: '80.0', soldout: false, cats: ['Best Sellers', 'Necklaces', 'Statement'], desc: 'Hand-woven silver thread necklace with cascading glass-bead fringe.\nFluid, scarf-like design.\nCan be styled multiple ways — wrapped, tied, belted, or worn long as a backlace.\nLightweight and comfortable for statement wear.\nMeasurements: length 43 in' },
  { slug: 'marrone-necklace', name: 'Marrone Necklace', img: 'https://assets.bigcartel.com/product_images/411862347/EE928A8E-3F07-42DA-AB30-E858455138C0.jpg?auto=format&fit=max&w=800', price: null, soldout: false, cats: ['Best Sellers', 'Spring/Summer', 'Necklaces'], desc: 'Brown Necklace: Chunky round beaded necklace.\nTwo lengths available - 22" & 33".\nElastic chord gives necklace a slight stretch.\nHypoallergenic, waterproof, and tarnish-free (can be worn shower, pool, ocean, etc.).\nHandmade with love in Los Angeles, CA <3' },
  { slug: 'marrone-bracelet-stack', name: 'Marrone Bracelet Stack', img: 'https://assets.bigcartel.com/product_images/403243167/IMG_6070.jpg?auto=format&fit=max&w=800', price: '115.0', soldout: false, cats: ['Best Sellers', 'Spring/Summer', 'Bracelets'], desc: 'Stack of 2 chunky round brown bracelets.\nElastic chord gives bracelet a slight stretch.\nHypoallergenic, waterproof, and tarnish-free (can be worn shower, pool, ocean, etc.).\nHandmade with love in Los Angeles, CA <3' },
  { slug: 'tiffany-co-elsa-peretti-lacquer-sevillana-pendant-necklace', name: 'Tiffany & Co. Elsa Peretti Lacquer Sevillana Pendant Necklace', img: 'https://assets.bigcartel.com/product_images/422068734/IMG_3888.jpeg?auto=format&fit=max&w=800', price: '330.0', soldout: false, cats: ['One-of-One', 'Necklaces'], desc: 'Black lacquer hardwood pendant on black cord.\nPendant diameter: 2".\nAdjustable cord length: 30".\nClassic Tiffany\'s x Elsa Peretti logo engraved on backside.\nFrom the Elsa Peretti Collection.\nMinor scuffing on backside of pendant.\nAuthentication available upon request.\nSourced with love in Los Angeles, CA <3' },
  { slug: 'ciottolo-necklace-black', name: 'Ciottolo Necklace - Black', img: 'https://assets.bigcartel.com/product_images/421131267/IMG_2948.jpeg?auto=format&fit=max&w=800', price: '80.0', soldout: false, cats: ['Best Sellers', 'Necklaces'], desc: '"Pebble" Necklace: Smooth, pebble-shaped black pendant on a sleek black cord.\nAdjustable drawstring cord: up to 30" for customizable length.\nPendant size: 1.75" width, 1.25" length.\nHypoallergenic, waterproof, and tarnish-free (safe for shower, pool, ocean, and everyday wear).\nDesigned with love in Los Angeles, CA <3' },
  { slug: 'tiered-pearl-choker', name: 'Tiered Pearl Choker', img: 'https://assets.bigcartel.com/product_images/415873692/IMG_7442.jpeg?auto=format&fit=max&w=800', price: '150.0', soldout: false, cats: ['Best Sellers', 'Necklaces', 'Statement'], desc: 'Gold-plated brass pearl choker.\nFeatures multiple hand-set pearl accents for a luminous, statement finish.\nEight-tier design that can be worn as a snug choker or styled looser for a layered look.\nAdjustable chain closure for a comfortable, custom fit.\nMeasurements: base length 11in; adjustable up to 18in.\nHandmade with unique variations and slight natural irregularities.' },
  { slug: 'midnight-cascade-choker', name: 'Midnight Cascade Choker', img: 'https://assets.bigcartel.com/product_images/414219912/unnamed.jpg?auto=format&fit=max&w=800', price: '110.0', soldout: false, cats: ['Best Sellers', 'Necklaces', 'Statement'], desc: 'Handmade beaded necklace with individually sewn glass beads in a cascading fringe shape featuring metallic blue thread and an adjustable stainless steel chain closure for customizable fit.\nLightweight and comfortable for extended wear, making it suitable for special occasions, nights out, or everyday elevated styling.\nHandmade - unique variations and slight irregularities.' },
  { slug: 'lora-necklace', name: 'Lora Statement Mirrored Waterfall Necklace', img: 'https://assets.bigcartel.com/product_images/409155639/6E4124C2-C83F-45FB-933D-4411DEFDC894_1_102_a.jpeg?auto=format&fit=max&w=800', price: '220.0', soldout: false, cats: ['Best Sellers', 'Necklaces', 'Statement'], desc: 'Gold-plated brass necklace with cascading hand-set mirrored accents.\nFeatures multiple hand-set mirrored accents for a dazzling effect.\nAdjustable chain for a comfortable, custom fit.\nMeasurements: Length 9 in; adjustable width up to 20 in.\nHandmade - unique variations and slight irregularities.' },
  { slug: 'mila-choker-silver', name: 'Mila Choker - Silver', img: 'https://assets.bigcartel.com/product_images/409155306/B5FFAF19-7ED1-4781-AED8-C5451A82A64F_1_105_c.jpeg?auto=format&fit=max&w=800', price: '80.0', soldout: false, cats: ['Best Sellers', 'Necklaces', 'Statement'], desc: 'Intricate lace trimmed choker with mirrored detailing.\nAdjustable fit with extra clasp length - one size fits all.\nLightweight and comfortable for all-day wear.\nAlso available in gold.\nHandmade - unique variations and slight irregularities.' },
  { slug: 'mila-choker-gold', name: 'Mila Choker - Gold', img: 'https://assets.bigcartel.com/product_images/409152315/863A5790-6649-498E-AC74-141FF512EFC5_1_105_c.jpeg?auto=format&fit=max&w=800', price: '80.0', soldout: false, cats: ['Best Sellers', 'Necklaces', 'Statement'], desc: 'Intricate lace trimmed choker with mirrored detailing.\nAdjustable fit with extra clasp length - one size fits all.\nLightweight and comfortable for all-day wear.\nAlso available in silver.\nHandmade - unique variations and slight irregularities.' },
  { slug: 'alba-earring', name: 'Alba Hoop Earring', img: 'https://assets.bigcartel.com/product_images/408991785/E1269588-3037-45B2-84AB-DC8A4B91D418_1_105_c.jpeg?auto=format&fit=max&w=800', price: '130.0', soldout: false, cats: ['Earrings'], desc: 'Lightweight hoop earrings with studded accents.\nWhite cubic zirconia studs on a gold-filled base.\nHypoallergenic posts.\nSecure hinge closure.\n26mm diameter.\nHypoallergenic, waterproof, and tarnish-free (can be worn in shower, pool, ocean, etc.).\nDesigned with love in Los Angeles, CA.' },
  { slug: 'gemella-stud-earrings', name: 'Gemella Stud Earrings', img: 'https://assets.bigcartel.com/product_images/423685908/IMG_5446.jpeg?auto=format&fit=max&w=800', price: '55.0', soldout: false, cats: ['Best Sellers', 'Earrings'], desc: 'Double oval bezel-set cubic zirconia stud earrings offering diamond-like sparkle in a minimal, sculptural silhouette.\n14K gold plated sterling silver base.\nBezel setting for a sleek, modern finish.\nButterfly back closure.\nHypoallergenic and water-resistant.\nDesigned with love in Los Angeles, CA.' },
  { slug: 'chiara-stud-earrings', name: 'Chiara Stud Earrings', img: 'https://assets.bigcartel.com/product_images/423686124/IMG_3609.jpeg?auto=format&fit=max&w=800', price: '65.0', soldout: false, cats: ['Best Sellers', 'Earrings'], desc: 'Single round bezel-set cubic zirconia stud earrings offering diamond-like sparkle in the most effortless, everyday silhouette.\nAvailable in two finishes: 14K gold plated sterling silver or 925 sterling silver.\nButterfly back closures.\nHypoallergenic and water resistant.\nDesigned with love in Los Angeles, CA.' },
  { slug: 'corallo-neckalce', name: 'Corallo Necklace', img: 'https://assets.bigcartel.com/product_images/409046229/IMG_5602.jpg?auto=format&fit=max&w=800', price: '90.0', soldout: false, cats: ['Best Sellers', 'Spring/Summer', 'Necklaces'], desc: '"Coral" Necklace: 18" necklace with dyed coral crisps.\nFinished with 3mm gold-filled beads & gold-filled clasp closure.\nEmail lunablujewels@gmail.com for all custom orders & additional chain lengths.\nHypoallergenic, waterproof, and tarnish-free (can be worn in shower, pool, ocean, etc.).\nHandmade with love in Los Angeles, CA <3' },
  { slug: 'corallo-waist-chain', name: 'Corallo Waist Chain', img: 'https://assets.bigcartel.com/product_images/387560700/DC207D1F-109F-4051-92D8-6F303D9A9B83_1_201_a.jpg?auto=format&fit=max&w=800', price: '145.0', soldout: false, cats: ['Best Sellers', 'Spring/Summer'], desc: '"Coral" Waist Chain: Finished with 3mm gold-filled beads & gold-filled clasp closure.\n2" extender.\nHypoallergenic, waterproof, and tarnish-free (can be worn in shower, pool, ocean, etc.).\nHandmade with love in Los Angeles, CA <3' },
  { slug: 'mother-of-pearl-shell-necklace', name: 'Mother of Pearl Shell Necklace', img: 'https://assets.bigcartel.com/product_images/403730298/854CD824-ACA6-4289-838F-97A37E461D3C_1_105_c.jpeg?auto=format&fit=max&w=800', price: '70.0', soldout: false, cats: ['Best Sellers', 'Spring/Summer', 'Necklaces'], desc: '45" leather chord with iridescent shell pendant.\nFully adjustable length - wear it as a choker, necklace, waist chain, or even bag chain.\nEmail lunablujewels@gmail.com for all custom orders & additional chain lengths.\nHandmade with love in Los Angeles, CA <3' },
  { slug: 'chunky-turquoise-bracelet-stack', name: 'Chunky Turquoise Bracelet Stack', img: 'https://assets.bigcartel.com/product_images/409046376/97FD6DAD-F7C6-430E-B72B-8E3357594B12_1_102_a.jpeg?auto=format&fit=max&w=800', price: '120.0', soldout: false, cats: ['Best Sellers', 'Spring/Summer', 'Bracelets'], desc: 'Stack of 3 chunky turquoise bracelets.\nOne-size - 6.3" - for additional sizing & custom orders email lunablujewels@gmail.com.\nElastic chord gives bracelet a slight stretch.\nHypoallergenic, waterproof, and tarnish-free (can be worn shower, pool, ocean, etc.).\nHandmade with love in Los Angeles, CA <3' },
  { slug: 'giove-body-chian', name: 'Giove Body Chain', img: 'https://assets.bigcartel.com/product_images/381388686/unnamed.jpg?auto=format&fit=max&w=800', price: '170.0', soldout: false, cats: ['Best Sellers', 'Spring/Summer'], desc: '14k gold-filled body chain (waterproof!!) with adjustable sizing at the neck and waist.\nFeatures a clasp closure that can attach anywhere on the chain.\nMeasures 22" at the neck, 10" across the body, and 30" at the waist.\nCustom sizing available upon request.\nHypoallergenic, waterproof, and tarnish-free (can be worn in shower, pool, ocean, etc.).\nHandmade with love in Los Angeles, CA.' },
  { slug: 'seashell-waist-chain', name: 'Seashell Waist Chain', img: 'https://assets.bigcartel.com/product_images/385019202/1BFD7BF5-CAB3-443D-8C44-B3339B0DAADE_1_201_a.jpeg?auto=format&fit=max&w=800', price: '115.0', soldout: false, cats: ['Best Sellers', 'Spring/Summer'], desc: 'Seashell waist chain with 14k gold-filled clasp closure and 2" extender.\nHypoallergenic, waterproof, and tarnish-free (can be worn in shower, pool, ocean, etc.).\nHandmade with love in Los Angeles, CA.' },
  { slug: 'turquoise-bracelet-stack', name: 'Turquoise Bracelet Stack', img: 'https://assets.bigcartel.com/product_images/387556941/0E54BCA2-922B-4305-B84E-CC243DD6CEA9_1_102_a.jpeg?auto=format&fit=max&w=800', price: null, soldout: false, cats: ['Best Sellers', 'Spring/Summer', 'Bracelets'], desc: 'Stack of 5 or 10 beaded turquoise bracelets.\nOne-size - 6.3" - for additional sizing & custom orders email lunablujewels@gmail.com.\nElastic chord gives bracelet a slight stretch.\nHypoallergenic, waterproof, and tarnish-free (can be worn shower, pool, ocean, etc.).\nHandmade with love in Los Angeles, CA <3' },
  { slug: 'collared-metal-choker-gold-filled', name: 'Collared Metal Choker - Gold Filled', img: 'https://assets.bigcartel.com/product_images/397145241/33A507ED-56AB-4DE4-967C-8C8D2A945DFD.jpeg?auto=format&fit=max&w=800', price: '180.0', soldout: false, cats: ['Best Sellers', 'Necklaces'], desc: 'Vintage inspired.\n14k gold-filled brass.\n5 inch diameter.\nOne size - adjustable.\nAlso available in sterling silver.\nHypoallergenic, waterproof, and tarnish-free (can be worn in shower, pool, ocean, etc.).\nDesigned with love in Los Angeles, CA.' },
  { slug: 'collared-metal-choker-silver', name: 'Collared Metal Choker - Silver', img: 'https://assets.bigcartel.com/product_images/397145598/F07C4FFB-C958-479A-ACF6-BFB8D5CA929C.jpeg?auto=format&fit=max&w=800', price: '180.0', soldout: false, cats: ['Best Sellers', 'Necklaces'], desc: 'Vintage inspired.\n0.925 sterling silver.\n5 inch diameter.\nOne size - adjustable.\nAlso available in gold.\nHypoallergenic, waterproof, and tarnish-free (can be worn in shower, pool, ocean, etc.).\nDesigned with love in Los Angeles, CA <3' },
  { slug: 'adjustable-gold-bangle', name: 'Adjustable Gold Bangle', img: 'https://assets.bigcartel.com/product_images/397145784/21366E4F-65DA-4093-9869-3BFB0F6AE076_1_105_c.jpeg?auto=format&fit=max&w=800', price: '130.0', soldout: false, cats: ['Best Sellers', 'Bracelets'], desc: 'Vintage inspired.\n14k gold-filled brass.\n2.5 inch diameter.\nOne size - adjustable.\nAlso available in sterling silver.\nHypoallergenic, waterproof, and tarnish-free (can be worn in shower, pool, ocean, etc.).\nDesigned with love in Los Angeles, CA.' },
  { slug: 'adjustable-silver-bangle', name: 'Adjustable Silver Bangle', img: 'https://assets.bigcartel.com/product_images/397146156/unnamed-1.jpg?auto=format&fit=max&w=800', price: '130.0', soldout: false, cats: ['Best Sellers', 'Bracelets'], desc: 'Vintage inspired.\n0.925 sterling silver.\n2.5 inch diameter.\nOne size - adjustable.\nAlso available in gold.\nHypoallergenic, waterproof, and tarnish-free (can be worn in shower, pool, ocean, etc.).\nDesigned with love in Los Angeles, CA <3' },
  { slug: 'ciottolo-necklace', name: 'Ciottolo Necklace', img: 'https://assets.bigcartel.com/product_images/402604887/2FED23E4-4F4F-49E1-89F6-3B3C606BCBE5_1_105_c.jpeg?auto=format&fit=max&w=800', price: '80.0', soldout: false, cats: ['Best Sellers', 'Necklaces'], desc: '"Pebble" Necklace: Silver/gold pebble-shaped pendant on black cord.\nAdjustable drawstring cord: up to 30" for customizable length.\nPendant size: 1.75" width, 1.25" length.\nHypoallergenic, waterproof, and tarnish-free (safe for shower, pool, ocean, and everyday wear).\nDesigned with love in Los Angeles, CA <3' },
  { slug: 'vintage-j-laurent-rhinestone-watch-tennis-bracelet-set', name: 'Vintage J. Laurent Rhinestone Watch & Tennis Bracelet Set', img: 'https://assets.bigcartel.com/product_images/423685608/IMG_9731.jpeg?auto=format&fit=max&w=800', price: '350.0', soldout: false, cats: ['One-of-One'], desc: 'Vintage gold-tone watch & bracelet set by J. Laurent.\nBezel-set crystal accents throughout the bracelet.\nDelicate round watch face with classic numeral markers.\nJewelry-inspired silhouette that doubles as a statement piece.\nQuartz movement.\nFold-over clasp closure for secure wear.\nCompared to diamond quality in brilliance and clarity.\nDesigned to be worn as jewelry first, watch second.\nWatch is functioning.\nSourced with love in Los Angeles, CA <3' },
  { slug: 'vintage-cavalli-silver-watch', name: 'Vintage Cavalli Sterling Silver Watch', img: 'https://assets.bigcartel.com/product_images/403216209/4B8EF732-AFBB-4FFA-B516-3FAD5988B778_1_105_c.jpeg?auto=format&fit=max&w=800', price: '345.0', soldout: false, cats: ['One-of-One'], desc: 'Roberto Cavalli sterling silver watch.\n.925 sterling silver stamped on inner band.\nWide, high-polish bangle-style band.\nBand width: 1.5in.\nIntegrated rectangular dial with silver-tone face.\nMinimalist design with no numerals.\nFits wrist size approx. 6–6.5in.\nFace size: approx. 20mm x 25mm.\nRoyal blue crown.\nWatch is not currently running.\nSourced with love in Los Angeles, CA <3' },
  { slug: 'calcolo-bracelet-stack', name: 'Calcolo Bracelet Stack', img: 'https://assets.bigcartel.com/product_images/403215432/ACF60640-FBE0-4F61-AE19-42FDF31E865A_1_105_c.jpeg?auto=format&fit=max&w=800', price: '90.0', soldout: false, cats: ['Best Sellers', 'Spring/Summer', 'Bracelets'], desc: 'Stack of 2 chunky white stone bracelets.\nElastic chord gives bracelet a slight stretch.\nHypoallergenic, waterproof, and tarnish-free (can be worn in shower, pool, ocean, etc.).\nHandmade with love in Los Angeles, CA.' },
  { slug: 'tennis-bracelet', name: 'Tennis Bracelet', img: 'https://assets.bigcartel.com/product_images/395106783/512A685F-8A1C-4A6E-9F86-0B189521AF34_1_102_o.jpeg?auto=format&fit=max&w=800', price: '175.0', soldout: false, cats: ['Bracelets'], desc: '925 Moissanite tennis bracelet.\n7" length.\n2.5mm width.\nPush clasp closure with double safety latch.\n9.55 carats, VVSD Color.\nGRA certificate readily available upon request.\nCompared to diamond quality in brilliance and clarity.\nEmail lunablujewels@gmail.com for additional sizing/customization.\nHypoallergenic, waterproof, and tarnish-free (can be worn in shower, pool, ocean, etc.).\nDesigned with love in Los Angeles, CA.' },
  { slug: 'tennis-necklace', name: 'Tennis Necklace', img: 'https://assets.bigcartel.com/product_images/395106831/1964CC57-2072-4E80-90DF-ED5B6C24E4A8_1_102_o.jpeg?auto=format&fit=max&w=800', price: '305.0', soldout: false, cats: ['Necklaces'], desc: '925 Moissanite tennis necklace.\n16" length.\n2.5mm.\nPush clasp closure with safety latch.\n9.55 carats, VVSD Color.\nGRA certificate readily available upon request.\nCompared to diamond quality in brilliance and clarity.\nEmail lunablujewels@gmail.com for additional lengths/customization.\nHypoallergenic, waterproof, and tarnish-free (can be worn in shower, pool, ocean, etc.).\nDesigned with love in Los Angeles, CA <3' },
  { slug: 'argento-cuff-gold-filled', name: 'Argento Cuff - Gold Filled', img: 'https://assets.bigcartel.com/product_images/380556036/unnamed-7.jpg.webp?auto=format&fit=max&w=800', price: '175.0', soldout: false, cats: ['Best Sellers'], desc: '14k gold filled.\nOne size - adjustable.\nMeasures 60mm in diameter.\nAlso available in sterling silver.\nLogo on inside of cuff.\nHypoallergenic, waterproof, and tarnish-free (can be worn in shower, pool, ocean, etc.).\nDesigned with love in Los Angeles, CA <3' },
  { slug: 'argento-cuff', name: 'Argento Cuff - Sterling Silver', img: 'https://assets.bigcartel.com/product_images/380560377/unnamed-1.jpg?auto=format&fit=max&w=800', price: '175.0', soldout: false, cats: ['Best Sellers'], desc: '.925 sterling silver.\nOne size - adjustable.\nMeasures 60mm in diameter.\nAlso available in 14k gold filled.\nLogo on inside of cuff.\nHypoallergenic, waterproof, and tarnish-free (can be worn in shower, pool, ocean, etc.).\nDesigned with love in Los Angeles, CA.' },
  { slug: 'the-amore-necklace', name: 'Amore Necklace', img: 'https://assets.bigcartel.com/product_images/380654799/0-2.jpeg?auto=format&fit=max&w=800', price: '105.0', soldout: false, cats: ['Best Sellers', 'Necklaces'], desc: '"Love" Necklace: 14k gold filled 16-inch paperclip chain necklace with heart locket pendant.\nAvailable in 3 chains: 1mm (Orbita), 2mm (Eclisse), 3mm (Cielo).\nEasily adjustable - clasp can be attached anywhere on chain - *size up for a looser fit*.\nEmail lunablujewels@gmail.com for all custom orders & additional chain lengths.\nHypoallergenic, waterproof, and tarnish-free (can be worn in shower, pool, ocean, etc.).\nHandmade with love in Los Angeles, CA <3' },
  { slug: 'best-friend-necklace-set', name: 'Best Friend Necklace Set', img: 'https://assets.bigcartel.com/product_images/384042849/unnamed-8.jpg?auto=format&fit=max&w=800', price: '75.0', soldout: false, cats: ['Best Sellers', 'Necklaces'], desc: '*Sold as a set - 2 necklaces.\nHalf heart necklaces engraved with the words "best friends".\n18k gold dipped hardware.\nApproximate length 16"' },
  { slug: 'phoebe-necklace', name: 'Giove Necklace', img: 'https://assets.bigcartel.com/product_images/395321925/2.jpeg?auto=format&fit=max&w=800', price: null, soldout: false, cats: ['Best Sellers', 'Necklaces'], desc: '14k gold-filled chain necklace with clasp closure.\nEasily adjustable - clasp can be attached anywhere along the chain.\nHypoallergenic, waterproof, & tarnish-free (can be worn shower, pool, ocean, etc.).\nEmail lunablujewels@gmail.com for all custom orders & additional chain lengths.\nHandmade with love in Los Angeles, CA.' },
  { slug: 'solare-necklace', name: 'Solare Necklace - Gold-Filled', img: 'https://assets.bigcartel.com/product_images/380700675/0-3.jpeg?auto=format&fit=max&w=800', price: null, soldout: false, cats: ['Best Sellers', 'Necklaces'], desc: '"Solar" Necklace: 14k gold-filled chain necklace with clasp closure.\nChain width: 3.3mm.\nClasp that can be attached anywhere along the chain for adjustability - *size up for a looser fit*.\nEmail lunablujewels@gmail.com for all custom orders & additional chain lengths.\nHypoallergenic, waterproof, & tarnish-free (can be worn shower, pool, ocean, etc.).\nHandmade with love in Los Angeles, CA.' },
  { slug: 'vintage-givenchy-chunky-necklace', name: 'Vintage Givenchy Chunky Necklace', img: 'https://assets.bigcartel.com/product_images/399256041/303CA5A5-CE67-4D7F-90E6-5FD9B57F0832_1_105_c.jpeg?auto=format&fit=max&w=800', price: '270.0', soldout: false, cats: ['One-of-One', 'Necklaces'], desc: 'One-of-one Givenchy necklace.\n18.5 inch length.\nClasp closure engraved with classic Givenchy logo.\nGold-tone metal.\nAuthentication certificate readily available upon request.\nSourced with love in Los Angeles, CA.' },
  { slug: 'solare-bracelet', name: 'Solare Bracelet', img: 'https://assets.bigcartel.com/product_images/376720480/0-2.jpeg?auto=format&fit=max&w=800', price: '65.0', soldout: false, cats: ['Best Sellers', 'Bracelets'], desc: '"Solar" Bracelet: 14k gold-filled chain bracelet.\nChain width: 3.3mm.\nEasily adjustable - clasp can be attached anywhere on chain - *size up for a looser fit*.\nHypoallergenic, waterproof, & tarnish-free (can be worn shower, pool, ocean, etc.).\nHandmade with love in Los Angeles, CA <3' },
  { slug: 'solare-ring', name: 'Solare Ring - Gold-Filled', img: 'https://assets.bigcartel.com/product_images/376019263/0.jpeg?auto=format&fit=max&w=800', price: '45.0', soldout: false, cats: ['Best Sellers', 'Rings'], desc: '"Solar" Ring: 14k gold filled loose-fitting true chain ring - 3.3mm wide.\nCan be stacked for a chunkier look.\nHypoallergenic, waterproof, and tarnish-free (can be worn in shower, pool, ocean, etc.).\nHandmade with love in Los Angeles, CA <3' },
  { slug: 'signet-ring', name: 'Signet Ring', img: 'https://assets.bigcartel.com/product_images/349404280/0.jpeg?auto=format&fit=max&w=800', price: '37.0', soldout: false, cats: ['Best Sellers', 'Rings'], desc: '14k gold-filled signet ring.\nSize 6.\nHypoallergenic, waterproof, and tarnish-free (can be worn in shower, pool, ocean, etc.).' },
  { slug: 'pave-hoops', name: 'Pavé Hoop Earrings', img: 'https://assets.bigcartel.com/product_images/377561008/0-15.jpeg?auto=format&fit=max&w=800', price: '75.0', soldout: false, cats: ['Best Sellers'], desc: 'Lightweight geometrical pavé hoop earring.\n14k gold filled with white/royal blue cubic zirconia accents.\nHinge closure.\nMeasures 20mm H x 15mm W.\nInner diameter - 9mm.\nHypoallergenic, waterproof, and tarnish-free (can be worn in shower, pool, ocean, etc.).' },
  { slug: 'mermaid-shell-earring', name: 'Mermaid Shell Earring', img: 'https://assets.bigcartel.com/product_images/393432252/unnamed.jpg?auto=format&fit=max&w=800', price: '80.0', soldout: false, cats: ['Best Sellers', 'Earrings'], desc: 'Lightweight shell stud earrings with butterfly lock.\nStainless steel with hypoallergenic posts.\nLength: 50mm.\nHypoallergenic, waterproof, and tarnish-free (can be worn in shower, pool, ocean, etc.).' },
  { slug: 'tab-earring', name: 'Tab Earring', img: 'https://assets.bigcartel.com/product_images/393431466/0771F326-DD96-428A-9C5D-E4DB17B03954_1_105_c.jpeg?auto=format&fit=max&w=800', price: '65.0', soldout: false, cats: ['Best Sellers', 'Earrings'], desc: 'Lightweight hoop earrings with butterfly lock.\nStainless steel with hypoallergenic posts.\nMeasures 25mm H.\nHypoallergenic, waterproof, and tarnish-free (can be worn in shower, pool, ocean, etc.).' },
  { slug: 'knotted-stud-earring-mixed-metal', name: 'Knotted Stud Earring - Mixed Metal', img: 'https://assets.bigcartel.com/product_images/395681709/97272868-768A-4B5A-B91E-D10142075F53_1_102_o.jpeg?auto=format&fit=max&w=800', price: '80.0', soldout: false, cats: ['Best Sellers', 'Earrings'], desc: 'Lightweight knotted accent stud earrings with butterfly lock.\nMixed metal finish.\nStainless steel with hypoallergenic posts.\nMeasures 30mm H x 20mm W.\nHypoallergenic, waterproof, and tarnish-free (can be worn in shower, pool, ocean, etc.).' },
  { slug: 'knotted-stud-earring', name: 'Knotted Stud Earring', img: 'https://assets.bigcartel.com/product_images/393430872/A59BC313-0B5E-4503-9BFE-99D7BA55D575_1_105_c.jpeg?auto=format&fit=max&w=800', price: '70.0', soldout: false, cats: ['Best Sellers', 'Earrings'], desc: 'Lightweight knotted accent stud earrings with butterfly lock.\nStainless steel with hypoallergenic posts.\nMeasures 30mm H x 20mm W.\nHypoallergenic, waterproof, and tarnish-free (can be worn in shower, pool, ocean, etc.).' },
  { slug: 'silvia-earring', name: 'Silvia Earring', img: 'https://assets.bigcartel.com/product_images/393436008/EF5C0A18-823E-408B-88ED-F296528BA19D_1_105_c.jpeg?auto=format&fit=max&w=800', price: '70.0', soldout: false, cats: ['Best Sellers', 'Earrings'], desc: 'Lightweight silver hoop earrings with flat backing.\nStainless steel with hypoallergenic posts.\nDiameter: 20mm.\nHypoallergenic, waterproof, and tarnish-free (can be worn in shower, pool, ocean, etc.).' },
  { slug: 'circular-stud-earring', name: 'Circular Stud Earring', img: 'https://assets.bigcartel.com/product_images/393432948/C50ED6E4-045B-4D53-861F-74214F27531B_1_105_c.jpeg?auto=format&fit=max&w=800', price: '70.0', soldout: false, cats: ['Best Sellers', 'Earrings'], desc: 'Lightweight stud earrings with butterfly lock.\nStainless steel with hypoallergenic posts.\nDiameter: 25mm.\nHypoallergenic, waterproof, and tarnish-free (can be worn in shower, pool, ocean, etc.).' },
  { slug: 'circularcz-stud-earring', name: 'Circular CZ Stud Earring', img: 'https://assets.bigcartel.com/product_images/393432738/2F188EAD-732C-40E3-B1A6-33F85203CBF5_1_105_c.jpeg?auto=format&fit=max&w=800', price: '90.0', soldout: false, cats: ['Best Sellers', 'Earrings'], desc: 'Lightweight stud earrings with clip-on closure.\nStainless steel with hypoallergenic posts.\nDiameter: 15mm.\nHypoallergenic, waterproof, and tarnish-free (can be worn in shower, pool, ocean, etc.).' },
  { slug: 'turquoise-charm-choker', name: 'Turquoise Charm Choker', img: 'https://assets.bigcartel.com/product_images/392170494/unnamed-6.jpg?auto=format&fit=max&w=800', price: '65.0', soldout: false, cats: ['Best Sellers', 'Necklaces'], desc: 'Beaded choker with turquoise gem beads & mini pendant.\n14.5" chain with clasp closure.\nEmail lunablujewels@gmail.com for all custom orders & additional chain lengths.\nHypoallergenic, waterproof, and tarnish-free (can be worn in shower, pool, ocean, etc.).\nHandmade with love in Los Angeles, CA.' },
  { slug: 'turquoise-beaded-necklace', name: 'Turquoise Beaded Necklace', img: 'https://assets.bigcartel.com/product_images/409140366/51E74F31-D2EE-48EE-AD14-EC655E0434AD_1_105_c.jpeg?auto=format&fit=max&w=800', price: '60.0', soldout: false, cats: ['Best Sellers', 'Spring/Summer', 'Necklaces'], desc: '4mm turquoise beaded necklace.\n16" length with secure clasp closure.\nLightweight and comfortable for all-day wear.\nMade with love in Los Angeles, CA.' },
  { slug: 'blue-beaded-necklace', name: 'Blue Beaded Necklace', img: 'https://assets.bigcartel.com/product_images/409149213/C7C31FAC-3E79-493F-A7A0-655480B37E3B_1_105_c.jpeg?auto=format&fit=max&w=800', price: '60.0', soldout: false, cats: ['Best Sellers', 'Spring/Summer', 'Necklaces'], desc: '5mm blue beaded necklace with gold-plated accents.\n16" length with secure clasp closure.\nLightweight and comfortable for all-day wear.\nMade with love in Los Angeles, CA.' },
  { slug: 'turquoise-necklace', name: 'Turquoise Necklace', img: 'https://assets.bigcartel.com/product_images/387681708/IMG_1443.jpeg?auto=format&fit=max&w=800', price: '60.0', soldout: false, cats: ['Best Sellers', 'Spring/Summer', 'Necklaces'], desc: '4mm turquoise beads accented with 4mm rhodium metal beads.\n16" or 18" chain with clasp closure.\nEmail lunablujewels@gmail.com for all custom orders & additional chain lengths.\nHypoallergenic, waterproof, and tarnish-free (can be worn in shower, pool, ocean, etc.).\nHandmade with love in Los Angeles, CA <3' },
  { slug: 'turquoise-chunky-beaded-necklace', name: 'Turquoise Chunky Beaded Necklace', img: 'https://assets.bigcartel.com/product_images/388413369/IMG_2281.jpeg?auto=format&fit=max&w=800', price: '105.0', soldout: false, cats: ['Best Sellers', 'Spring/Summer', 'Necklaces'], desc: '16" necklace with 10mm turquoise beads.\nSterling silver clasp closure.\nHypoallergenic, waterproof, and tarnish-free (can be worn in shower, pool, ocean, etc.).\nHandmade with love in Los Angeles, CA <3' },
  { slug: 'stella-starfish-turqouise-beaded-necklace', name: 'Stella Starfish Turquoise Beaded Necklace', img: 'https://assets.bigcartel.com/product_images/389773404/E2BA490F-5206-4D7B-95F1-E1AE04BEDF6B_1_105_c.jpeg?auto=format&fit=max&w=800', price: '140.0', soldout: false, cats: ['Spring/Summer', 'Necklaces'], desc: '10mm turquoise beads with gold plated starfish charm.\n20" necklace with 63mm pendant.\n14k gold-filled clasp closure.\nHandmade with love in Los Angeles, CA <3' },
  { slug: 'royal-blu-choker', name: 'Royal Blü Choker', img: 'https://assets.bigcartel.com/product_images/426229380/8A530DE9-0A96-4EDE-9F92-6D080A4A1313_1_105_c.jpeg?auto=format&fit=max&w=800', price: '65.0', soldout: false, cats: ['Spring/Summer', 'Necklaces'], desc: 'Beaded choker with royal blue seed beads.\n14" with clasp closure.\nEmail lunablujewels@gmail.com for all custom orders & additional colors.\nHypoallergenic, waterproof, and tarnish-free (can be worn in shower, pool, ocean, etc.).\nHandmade with love in Los Angeles, CA <3' },
  { slug: 'royal-blue-eye-choker', name: 'Royal Blu Eye Choker', img: 'https://assets.bigcartel.com/product_images/388388277/747CECB3-238C-445C-9AB1-EF9229012D2D_1_105_c.jpeg?auto=format&fit=max&w=800', price: '65.0', soldout: false, cats: ['Spring/Summer', 'Necklaces'], desc: '14" beaded choker with royal blue seed beads & gold-filled evil eye charm.\nGold-filled clasp closure.\nHypoallergenic, waterproof, and tarnish-free (can be worn in shower, pool, ocean, etc.).\nHandmade with love in Los Angeles, CA.' },
  { slug: 'agate-chunky-beaded-necklace', name: 'Agate Chunky Beaded Necklace - Royal Blue', img: 'https://assets.bigcartel.com/product_images/388387902/43FBAADE-BC9B-4C93-9B6C-59E6F2BA4486_1_105_c.jpeg?auto=format&fit=max&w=800', price: '105.0', soldout: false, cats: ['Spring/Summer', 'Necklaces'], desc: '16" necklace with royal blue 10mm agate beads.\nSterling silver clasp closure.\nHypoallergenic, waterproof, and tarnish-free (can be worn in shower, pool, ocean, etc.).\nHandmade with love in Los Angeles, CA.' },
  { slug: 'agate-chunky-beaded-necklace-yellow', name: 'Agate Chunky Beaded Necklace - Yellow', img: 'https://assets.bigcartel.com/product_images/388412703/1.jpeg?auto=format&fit=max&w=800', price: '105.0', soldout: false, cats: ['Spring/Summer', 'Necklaces'], desc: '16" necklace with yellow 10mm agate beads.\nSterling silver clasp closure.\nHypoallergenic, waterproof, and tarnish-free (can be worn in shower, pool, ocean, etc.).\nHandmade with love in Los Angeles, CA.' },
  { slug: 'agate-chunky-beaded-necklace-jade', name: 'Agate Chunky Beaded Necklace - Jade Green', img: 'https://assets.bigcartel.com/product_images/388413081/IMG_2289.jpeg?auto=format&fit=max&w=800', price: '105.0', soldout: false, cats: ['Spring/Summer', 'Necklaces'], desc: '16" necklace with jade 10mm agate beads.\nSterling silver clasp closure.\nHypoallergenic, waterproof, and tarnish-free (can be worn in shower, pool, ocean, etc.).\nHandmade with love in Los Angeles, CA.' },
  { slug: 'agate-chunky-beaded-necklace-pink', name: 'Agate Chunky Beaded Necklace - Pink', img: 'https://assets.bigcartel.com/product_images/388412373/E4595F75-BA59-4CAA-BDD2-E1D143C959CF_1_105_c.jpeg?auto=format&fit=max&w=800', price: '105.0', soldout: false, cats: ['Spring/Summer', 'Necklaces'], desc: '16" necklace with pink 10mm agate beads.\nSterling silver clasp closure.\nHypoallergenic, waterproof, and tarnish-free (can be worn in shower, pool, ocean, etc.).\nHandmade with love in Los Angeles, CA.' },
  { slug: 'agate-chunky-beaded-bracelet', name: 'Agate Chunky Beaded Bracelet', img: 'https://assets.bigcartel.com/product_images/388410981/CE5C7102-27F3-4899-BC7B-BCF20B91CECA_1_102_o.jpeg?auto=format&fit=max&w=800', price: '65.0', soldout: false, cats: ['Spring/Summer', 'Bracelets'], desc: '10mm agate beaded bracelet.\nElastic cord for a slight stretch.\nHypoallergenic, waterproof, and tarnish-free (can be worn in shower, pool, ocean, etc.).\nHandmade with love in Los Angeles, CA.' },
  { slug: 'the-luna-pearl-necklace', name: 'Luna Pearl Necklace', img: 'https://assets.bigcartel.com/product_images/380627016/4.jpg?auto=format&fit=max&w=800', price: '145.0', soldout: false, cats: ['Spring/Summer', 'Necklaces'], desc: '"Moon" Pearl Necklace: 14k gold-filled necklace with 3 millimeter beads separated by pink freshwater pearls.\n17" chain with clasp closure - perfect for layering with other pieces.\nEmail lunablujewels@gmail.com for all custom orders & additional chain lengths.\nHypoallergenic, waterproof, and tarnish-free (can be worn in shower, pool, ocean, etc.).\nHandmade with love in Los Angeles, CA <3' },
  { slug: 'the-perla-charm-choker', name: 'Perla Charm Choker', img: 'https://assets.bigcartel.com/product_images/379684947/0.jpeg?auto=format&fit=max&w=800', price: '50.0', soldout: false, cats: ['Spring/Summer', 'Necklaces'], desc: '"Pearl" Charm Choker: Pearl choker with 3mm fresh water pearls & gold filled mini coin charm.\n14" chain with clasp closure.\nEmail lunablujewels@gmail.com for all custom orders & additional chain lengths.\nHypoallergenic, waterproof, and tarnish-free (can be worn in shower, pool, ocean, etc.).\nHandmade with love in Los Angeles, CA <3' },
  { slug: 'the-mare-necklace', name: 'Mare Necklace', img: 'https://assets.bigcartel.com/product_images/381513468/IMG_2116-2.jpg?auto=format&fit=max&w=800', price: '75.0', soldout: false, cats: ['Spring/Summer', 'Necklaces'], desc: '"Sea" Necklace: 18" necklace with small shell crisps & gold-filled clasp closure.\nEmail lunablujewels@gmail.com for all custom orders & additional chain lengths.\nHypoallergenic, waterproof, and tarnish-free (can be worn in shower, pool, ocean, etc.).\nHandmade with love in Los Angeles, CA <3' },
  { slug: 'layerable-spring-choker', name: 'Multi-Charm Spring Choker', img: 'https://assets.bigcartel.com/product_images/380628147/crop+out+top.jpg?auto=format&fit=max&w=800', price: '50.0', soldout: false, cats: ['Spring/Summer'], desc: 'Beaded choker with green, pink, or blue gem beads & multiple gold-filled mini coin pendants.\n15" chain with clasp closure.\nHypoallergenic, waterproof, and tarnish-free (can be worn in shower, pool, ocean, etc.).\nHandmade with love in Los Angeles, CA.' },
  { slug: 'the-summer-choker', name: 'Summer Choker', img: 'https://assets.bigcartel.com/product_images/332011038/169063917_3534371053335208_8623979474196551258_n.jpg?auto=format&fit=max&w=800', price: '50.0', soldout: false, cats: ['Spring/Summer'], desc: 'Beaded choker with rainbow seed beads/pearl(s).\n14" chain with clasp closure.\nEmail for all custom orders & additional chain lengths.\nHypoallergenic, waterproof, and tarnish-free (can be worn in shower, pool, ocean, etc.).\nHandmade with love in Los Angeles, CA.' },
  { slug: 'the-summer-waist-chain', name: 'Summer Waist Chain', img: 'https://assets.bigcartel.com/product_images/331559343/unnamed.jpg?auto=format&fit=max&w=800', price: '115.0', soldout: false, cats: ['Spring/Summer'], desc: 'Beaded waist chain with rainbow or white seed beads (option to add single 3mm freshwater pearls).\nClasp closure.\nHypoallergenic, waterproof, and tarnish-free (can be worn in shower, pool, ocean, etc.).\nHandmade with love in Los Angeles, CA.' },
  { slug: 'vintage-cartier-santos-ronde-quartz-watch', name: 'Vintage Cartier Santos Ronde Quartz Watch', img: 'https://assets.bigcartel.com/product_images/409492068/99370A5F-E05E-489F-9DA5-1D4C278109A6_1_102_o.jpeg?auto=format&fit=max&w=800', price: '2800.0', soldout: true, cats: ['One-of-One'], desc: 'Collection: Santos de Cartier.\nEra: late 1980s – early 1990s.\nFits approx. 6" wrist (additional links can be added or removed).\nCase: Stainless steel with 18k yellow gold accents.\nCase Diameter: ~30mm.\nGrey/silver minimalist dial with gold-tone hands.\nStainless steel bezel with exposed screw design.\nCartier Caliber 81 quartz, Swiss-made.\nSteel crown set with a blue cabochon.\nExcellent condition - needs battery.\nRef number: 819132729.\nSourced with love in Los Angeles, CA.' },
  { slug: 'vintage-gucci-leather-band-watch', name: 'Vintage Gucci Leather Band Watch', img: 'https://assets.bigcartel.com/product_images/400471809/9E109F0F-8AEB-4999-A09C-96EF208823BA_1_105_c.jpeg?auto=format&fit=max&w=800', price: '325.0', soldout: false, cats: ['One-of-One'], desc: 'Gucci 1700S vintage watch with leather bangle band (24mm width).\nFeatures gold plated accents, 20mm x 20mm face, and fits wrist sizes 6-6.5in.\nThe watch is not currently functioning.\nSourced with love in Los Angeles, CA.' },
  { slug: 'vintage-gucci-1400l-gold-bangle-watch', name: 'Vintage Gucci 1400L Gold Bangle Watch', img: 'https://assets.bigcartel.com/product_images/405160257/3DD3B382-528C-4B2F-BF0D-027D9284ECA5_1_105_c.jpeg?auto=format&fit=max&w=800', price: '415.0', soldout: false, cats: ['One-of-One'], desc: 'Vintage Gucci 1400L.\nGold-plated stainless steel.\nHorsebit bangle design.\n25mm round case.\nWhite dial.\nInner circumference: 6.5 inches.\nWatch is not currently functioning.\nA chic silhouette reminiscent of Cartier\'s Baignoire design.\nSourced with love in Los Angeles, CA.' },
  { slug: 'vintage-gucci-puffed-mariner-chain-watch', name: 'Vintage Gucci Puffed Mariner Chain Watch', img: 'https://assets.bigcartel.com/product_images/389333148/F9E573A1-F9E5-4AC1-A636-50C94B173AFE_1_105_c.jpeg?auto=format&fit=max&w=800', price: '315.0', soldout: false, cats: ['One-of-One'], desc: 'Silver tone Gucci watch with puffed mariner band.\nStainless steel adjustable strap buckle with 3 notches.\nFace 1".\nLength 8".\nBlack dial.\nWater resistant.\nWatch is not currently running.\nSourced with love in Los Angeles, CA <3' },
  { slug: 'vintage-two-toned-ysl-chronograph-watch', name: 'Vintage Two-Toned YSL Chronograph Watch', img: 'https://assets.bigcartel.com/product_images/395256435/IMG_3940.jpeg?auto=format&fit=max&w=800', price: '490.0', soldout: false, cats: ['One-of-One'], desc: 'Rare two-toned Saint Laurent watch with quadruple sub-dial display.\nStainless steel case with gold tone accents and blue face featuring roman numeral markers.\nUnisex design with date display for added functionality.\nThe watch is currently running.\nSourced with love in Los Angeles, CA.' },
  { slug: 'ysl-black-stone-accent-ring-size-6', name: 'YSL Black Stone Accent Ring - Size 6', img: 'https://assets.bigcartel.com/product_images/394120179/IMG_1870.jpeg?auto=format&fit=max&w=800', price: '600.0', soldout: false, cats: ['One-of-One'], desc: 'Vintage Saint Laurent accent ring with 24KT Gold plated frame, featuring a smooth black cabochon glass oval measuring 35mm in length.\nIn excellent condition with no tarnishing, this rare color way was made in France.\nAuthentication certificate is available upon request.\nSourced with love in Los Angeles, CA.' },
  { slug: 'vintage-givenchy-brick-earring', name: 'Vintage Givenchy Brick Earring', img: 'https://assets.bigcartel.com/product_images/399774903/B698BC08-CD71-42E7-B3CA-2B5764C99E18_1_105_c.jpeg?auto=format&fit=max&w=800', price: '170.0', soldout: false, cats: ['One-of-One'], desc: 'One-of-one vintage Givenchy earring.\nGold tone brick pattern.\nClip ons - hinge closure.\nLightweight.\nClassic Givenchy logo engraved on backside.\nAuthentication certificate readily available upon request.\nSourced with love in Los Angeles, CA <3' },
  { slug: 'blue-vintage-christian-dior-clip-on', name: 'Blue Vintage Christian Dior Clip On Earrings', img: 'https://assets.bigcartel.com/product_images/388978683/unnamed.jpg?auto=format&fit=max&w=800', price: '265.0', soldout: false, cats: ['One-of-One'], desc: 'One-of-one lightweight Christian Dior earring.\nClip on.\nBlue crystal & white CZ detailing on gold-tone metal.\nClassic Christian Dior logo engraved on backside.\nMeasures about 2.5cm top to bottom.\nAuthentication certificate readily available upon request.\nSourced with love in Los Angeles, CA <3' },
  { slug: 'vintage-christian-dior', name: 'Vintage Christian Dior CZ Clip On Earrings', img: 'https://assets.bigcartel.com/product_images/383045619/0-16.jpeg?auto=format&fit=max&w=800', price: '265.0', soldout: false, cats: ['One-of-One'], desc: 'One-of-one lightweight Christian Dior earring.\nClip on.\nWhite CZ detailing on gold-tone metal.\nClassic Christian Dior logo engraved on backside.\nMeasures 3cm top to bottom.\nAuthentication certificate readily available upon request.\nSourced with love in Los Angeles, CA <3' },
  { slug: 'vintage-fendi-studs', name: 'Vintage Fendi Stud Earrings', img: 'https://assets.bigcartel.com/product_images/383045127/0-1.jpeg?auto=format&fit=max&w=800', price: '255.0', soldout: false, cats: ['One-of-One'], desc: 'One-of-one lightweight Fendi stud earring.\n14k gold filled lock closure.\nGold-tone metal with the classic Fendi Logo.\nWidest section measures 2.25cm.\nAuthentication certificate readily available upon request.\nSourced with love in Los Angeles, CA.' },
  { slug: 'vintage-ysl-clip-on-studs', name: 'Vintage YSL Clip On Stud Earrings', img: 'https://assets.bigcartel.com/product_images/383045409/0-10.jpeg?auto=format&fit=max&w=800', price: '255.0', soldout: false, cats: ['One-of-One'], desc: 'One-of-one circular YSL clip on stud earring.\nLightweight.\nGold-tone metal.\nClassic YSL logo engraved on backside.\n2cm diameter.\nAuthentication certificate readily available upon request.\nSourced with love in Los Angeles, CA <3' },
  { slug: 'vintage-ysl-cabochon-clip-on-earrings', name: 'Vintage YSL Cabochon Clip On Earrings', img: 'https://assets.bigcartel.com/product_images/389749362/unnamed.png?auto=format&fit=max&w=800', price: '290.0', soldout: false, cats: ['One-of-One'], desc: 'One-of-one vintage Yves Saint Laurent earring.\nClip on - hinge closure.\nLightweight.\nFaux amethyst cabochon glass detailing.\nClassic YSL logo engraved on backside.\nMeasures 1" height x .8" width.\nAuthentication certificate readily available upon request.\nSourced with love in Los Angeles, CA.' },
  { slug: 'vintage-christian-dior-clip-ons', name: 'Vintage Christian Dior Clip On Hoop Earrings', img: 'https://assets.bigcartel.com/product_images/383045232/0-5.jpeg?auto=format&fit=max&w=800', price: '135.0', soldout: false, cats: ['One-of-One'], desc: 'One-of-one Christian Dior clip on hoop earring.\nLightweight.\nCZ accent on gold-tone metal.\nClassic Christian Dior logo engraved on backside.\nMeasures 2.5cm top to bottom.\nAuthentication certificate readily available upon request.\nSourced with love in Los Angeles, CA.' },
  { slug: 'vintage-givenchy-white-resin-earrings', name: 'Vintage Givenchy White Resin Earrings', img: 'https://assets.bigcartel.com/product_images/389877813/3F2DBCF0-E1AE-4665-88D0-2EEF6B6C0CE8_4_5005_c.jpeg?auto=format&fit=max&w=800', price: '270.0', soldout: false, cats: ['One-of-One'], desc: 'One-of-one vintage Givenchy earring.\nDouble white resin gemstone.\nClip ons - hinge closure.\nLightweight.\nClassic Givenchy logo engraved on backside.\nAuthentication certificate readily available upon request.\nSourced with love in Los Angeles, CA <3' },
  { slug: 'gold-luna-bracelet-8mm', name: 'Gold Luna Bracelet - 8mm', img: 'https://assets.bigcartel.com/product_images/392169969/unnamed.jpg?auto=format&fit=max&w=800', price: '195.0', soldout: false, cats: ['Bracelets'], desc: 'Gold "Moon" Bracelet: 14k gold-filled chunky bracelet with 8 millimeter beads.\nAvailable for custom order in silver & rose gold.\nEmail lunablujewels@gmail.com to add charms/color.\nElastic chord gives bracelet a slight stretch for easy on and off.\nHypoallergenic, waterproof, and tarnish-free (can be worn in shower, pool, ocean, etc.).\nHandmade with love in Los Angeles, CA.' },
  { slug: 'terra-bracelet', name: 'Terra Bracelet', img: 'https://assets.bigcartel.com/product_images/384344730/IMG_2223.jpeg?auto=format&fit=max&w=800', price: '45.0', soldout: false, cats: ['Bracelets'], desc: '14k gold-filled enamel chain with colored accents.\nClasp closure.\nHypoallergenic, waterproof, and tarnish-free (can be worn in shower, pool, ocean, etc.).\nHandmade with love in Los Angeles, CA.' },
  { slug: 'the-silver-luna-bracelet-2mm', name: 'Silver Luna Bracelet - 2mm', img: 'https://assets.bigcartel.com/product_images/380584989/1-13.jpeg-pdf.jpg?auto=format&fit=max&w=800', price: '40.0', soldout: false, cats: ['Bracelets'], desc: 'Sterling silver bracelet with 2 millimeter beads.\nCurrently available to shop in gold & available for custom order in rose gold.\nElastic chord for easy application.\nHypoallergenic, waterproof, and tarnish-free (can be worn in shower, pool, ocean, etc.).\nHandmade with love in Los Angeles, CA.' },
  { slug: 'the-saturno-bracelet', name: 'Saturno Bracelet', img: 'https://assets.bigcartel.com/product_images/380585010/1-16-1-pdf.jpg?auto=format&fit=max&w=800', price: '68.0', soldout: false, cats: ['Bracelets'] },
  { slug: 'the-mixed-metal-bracelet', name: 'Mixed Metal Bracelet', img: 'https://assets.bigcartel.com/product_images/380585079/0-3-pdf.jpg?auto=format&fit=max&w=800', price: '60.0', soldout: false, cats: ['Bracelets'] },
  { slug: 'luna-bundle', name: 'Luna Bundle', img: 'https://assets.bigcartel.com/product_images/374383870/129218318_3562878027132933_6491509323319750100_n.jpg?auto=format&fit=max&w=800', price: '140.0', soldout: false, cats: ['Bracelets'] },
  { slug: 'bubble-initial-necklace', name: 'Bubble Initial Necklace', img: 'https://assets.bigcartel.com/product_images/375563455/0-12.jpeg?auto=format&fit=max&w=800', price: '130.0', soldout: false, cats: ['Necklaces'] },
  { slug: 'cowboy-charm-necklace', name: 'Cowboy Charm Necklace', img: 'https://assets.bigcartel.com/product_images/384043155/unnamed-14.jpg?auto=format&fit=max&w=800', price: '55.0', soldout: false, cats: ['Necklaces'] },
  { slug: 'the-gold-luna-ring-2mm', name: 'Gold Luna Ring - 2mm', img: 'https://assets.bigcartel.com/product_images/380618559/0.jpeg?auto=format&fit=max&w=800', price: '17.0', soldout: false, cats: ['Rings'] },
  { slug: 'the-gold-luna-ring-3mm', name: 'Gold Luna Ring - 3mm', img: 'https://assets.bigcartel.com/product_images/380618565/0-1.jpeg?auto=format&fit=max&w=800', price: '18.0', soldout: false, cats: ['Rings'] },
  { slug: 'the-perla-ring', name: 'Perla Ring', img: 'https://assets.bigcartel.com/product_images/379463520/0-17.jpeg?auto=format&fit=max&w=800', price: '20.0', soldout: false, cats: ['Rings'] },
  { slug: 'the-gold-luna-ring-4mm', name: 'Gold Luna Ring - 4mm', img: 'https://assets.bigcartel.com/product_images/380618610/0-2.jpeg?auto=format&fit=max&w=800', price: '20.0', soldout: false, cats: ['Rings'] },
  { slug: 'the-silver-luna-ring-2mm', name: 'Silver Luna Ring - 2mm', img: 'https://assets.bigcartel.com/product_images/380621061/1-8.jpeg.jpg?auto=format&fit=max&w=800', price: '10.0', soldout: false, cats: ['Rings'] },
  { slug: 'the-silver-luna-ring-3mm', name: 'Silver Luna Ring - 3mm', img: 'https://assets.bigcartel.com/product_images/380621310/1-10.jpeg.jpg?auto=format&fit=max&w=800', price: '12.0', soldout: false, cats: ['Rings'] },
  { slug: 'solare-ring-rhodium', name: 'Solare Ring - Rhodium', img: 'https://assets.bigcartel.com/product_images/385021128/IMG_3450.jpeg?auto=format&fit=max&w=800', price: '45.0', soldout: false, cats: ['Rings'] },
  { slug: 'moissanite-oval-stud-earrings', name: 'Moissanite Oval Stud Earrings', img: 'https://assets.bigcartel.com/product_images/423685215/IMG_5470.jpeg?auto=format&fit=max&w=800', price: '105.0', soldout: false, cats: ['Earrings'] },
  { slug: 'the-nocturne-stack', name: 'The Nocturne Stack', img: 'https://assets.bigcartel.com/product_images/404923938/3CB75A2C-02CB-4061-99A1-2FB0788E5C39_1_105_c.jpeg?auto=format&fit=max&w=800', price: '140.0', soldout: false, cats: ["The Men's Edit"] },
  { slug: 'the-mykonos-stack', name: 'The Mykonos Stack', img: 'https://assets.bigcartel.com/product_images/404931087/70FAC6AA-9DFA-4012-93A3-725FD367A31B_1_105_c.jpeg?auto=format&fit=max&w=800', price: '140.0', soldout: false, cats: ["The Men's Edit"] },
  { slug: 'the-verde-stack', name: 'The Verde Stack', img: 'https://assets.bigcartel.com/product_images/404924064/AC2BE1FC-3942-45D2-B2FC-244FFDCCACB9_1_105_c.jpeg?auto=format&fit=max&w=800', price: '140.0', soldout: false, cats: ["The Men's Edit"] },
  { slug: 'the-link', name: 'The Link', img: 'https://assets.bigcartel.com/product_images/404947314/79E5B662-AD74-467B-A0BF-6518AC9AC5FF_1_105_c.jpeg?auto=format&fit=max&w=800', price: '165.0', soldout: false, cats: ["The Men's Edit"] },
  { slug: 'the-core', name: 'The Core', img: 'https://assets.bigcartel.com/product_images/404930382/761C8369-BCAA-4BDA-9BAE-DCF401102AF7_1_105_c.jpeg?auto=format&fit=max&w=800', price: '52.0', soldout: false, cats: ["The Men's Edit"] },
  { slug: 'the-core-ii', name: 'The Core II', img: 'https://assets.bigcartel.com/product_images/404930346/345B4637-A499-4A4C-937A-313638DFC58D_1_105_c.jpeg?auto=format&fit=max&w=800', price: '52.0', soldout: false, cats: ["The Men's Edit"] },
  { slug: 'the-fade-black', name: 'The Fade - Black', img: 'https://assets.bigcartel.com/product_images/404930664/392E915C-9ADC-4064-8CF4-7344CE78CC91_1_105_c.jpeg?auto=format&fit=max&w=800', price: '52.0', soldout: false, cats: ["The Men's Edit"] },
  { slug: 'the-fade-brown', name: 'The Fade - Brown', img: 'https://assets.bigcartel.com/product_images/404929506/0319B1FA-9110-47FE-8C03-335C669C18DE_1_105_c.jpeg?auto=format&fit=max&w=800', price: '52.0', soldout: false, cats: ["The Men's Edit"] },
  { slug: 'the-fade-sandstone', name: 'The Fade - Sandstone', img: 'https://assets.bigcartel.com/product_images/404930793/3921FA9A-5D17-477A-8864-007761A8421F_1_105_c.jpeg?auto=format&fit=max&w=800', price: '52.0', soldout: false, cats: ["The Men's Edit"] },
  { slug: 'the-fade-blue', name: 'The Fade - Blue', img: 'https://assets.bigcartel.com/product_images/404930574/F78B7DA1-17D0-4034-939A-183504621B23_1_105_c.jpeg?auto=format&fit=max&w=800', price: '52.0', soldout: false, cats: ["The Men's Edit"] },
  { slug: 'the-fade-green', name: 'The Fade - Green', img: 'https://assets.bigcartel.com/product_images/404930424/376C5A33-26F0-4D71-A765-500ACE32AB56_1_105_c.jpeg?auto=format&fit=max&w=800', price: '52.0', soldout: false, cats: ["The Men's Edit"] },
];

export const FEATURED_SLUGS = [
  'isla-necklace', 'cora-wrap-scarf-necklace', 'marrone-necklace', 'marrone-bracelet-stack',
  'ciottolo-necklace-black', 'tiered-pearl-choker', 'midnight-cascade-choker', 'lora-necklace',
];

export function formatPrice(price: string | null): string {
  if (!price) return 'Contact for price';
  const n = parseFloat(price);
  if (isNaN(n)) return 'Contact for price';
  return '$' + n.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 });
}

export function getProductBySlug(slug: string): Product | undefined {
  return CATALOG.find(p => p.slug === slug);
}

export function getProductsByCategory(cat: string): Product[] {
  if (cat === 'All') return CATALOG;
  return CATALOG.filter(p => p.cats.includes(cat));
}

export const CATEGORIES = [
  'All', 'Best Sellers', 'Spring/Summer', 'One-of-One',
  'Bracelets', 'Necklaces', 'Rings', 'Earrings', "The Men's Edit", 'Statement',
];

export const SHOP_CATS = [
  { label: 'Best Sellers',  cat: 'Best Sellers',  img: 'https://assets.bigcartel.com/product_images/409155333/91ABA159-7EAA-4AF5-A5C7-4AB15B3AD8B2_1_102_a.jpeg?auto=format&fit=max&w=800' },
  { label: 'Spring/Summer', cat: 'Spring/Summer', img: 'https://assets.bigcartel.com/product_images/411862347/EE928A8E-3F07-42DA-AB30-E858455138C0.jpg?auto=format&fit=max&w=800' },
  { label: 'One-of-One',   cat: 'One-of-One',   img: 'https://assets.bigcartel.com/product_images/421574505/38232BDD-44BC-4496-A6B0-7890172C307B_1_102_o.jpeg?auto=format&fit=max&w=800' },
  { label: 'All Products', cat: 'All',           img: 'https://assets.bigcartel.com/product_images/415873692/IMG_7442.jpeg?auto=format&fit=max&w=800' },
];
